# Generated by Django 2.2.3 on 2019-07-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='NaN', max_length=4, verbose_name='技术等级')),
                ('rate', models.FloatField(default=0, verbose_name='提成率')),
            ],
        ),
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('name', models.CharField(default='NaN', max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(default='NaN', max_length=11, verbose_name='联系电话')),
                ('unionCode', models.CharField(default='NaN', max_length=50, verbose_name='unionCode')),
                ('loginCode', models.CharField(default='NaN', max_length=50, verbose_name='微信登录凭证')),
                ('jobNumber', models.CharField(default='NaN', max_length=10, verbose_name='工号')),
                ('address', models.CharField(default='NaN', max_length=50, verbose_name='地址')),
                ('hiredate', models.DateTimeField(blank=True, verbose_name='入职时间')),
                ('hire', models.CharField(choices=[('审核中', '审核中'), ('已就职', '已就职'), ('已离职', '已离职')], default='审核中', max_length=3, verbose_name='就职状态')),
                ('dimissionTime', models.DateTimeField(blank=True, verbose_name='离职时间')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.Level', verbose_name='用户等级')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
