# Generated by Django 2.2.3 on 2019-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='hire',
            field=models.CharField(choices=[('审核中', '审核中'), ('已就职', '已就职'), ('已离职', '已离职')], default='审核中', max_length=3, verbose_name='就职状态'),
        ),
    ]
