# Generated by Django 2.2.3 on 2019-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='NaN', max_length=10, verbose_name='服务商')),
                ('typ', models.CharField(default='NaN', max_length=10, verbose_name='用户种类')),
            ],
        ),
    ]
