# Generated by Django 2.2.3 on 2019-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190710_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='hiredate',
            field=models.DateTimeField(blank=True, verbose_name='入职时间'),
        ),
    ]
