# Generated by Django 2.2.3 on 2019-07-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_vipusertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='vipUserType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.VipUserType', verbose_name='服务商-用户类型'),
        ),
    ]
