# Generated by Django 2.2.3 on 2019-07-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_level_vipusertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='vipUserType',
        ),
    ]
