# Generated by Django 2.2.3 on 2019-07-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20190715_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='技术等级权重'),
        ),
    ]
