# Generated by Django 2.2.3 on 2019-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_level_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('大师', '大师'), ('专家', '专家'), ('高级', '高级'), ('中级', '中级'), ('初级', '初级')], default='初级', max_length=4, verbose_name='技术等级'),
        ),
    ]
