# Generated by Django 2.2.3 on 2019-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_remove_level_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='dimissionTime',
            field=models.DateTimeField(null=True, verbose_name='离职时间'),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='hiredate',
            field=models.DateTimeField(null=True, verbose_name='入职时间'),
        ),
    ]
