# Generated by Django 2.2.3 on 2019-07-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_auto_20190717_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vipUser', to='office.Level', verbose_name='用户等级'),
        ),
    ]
