# Generated by Django 2.2.3 on 2019-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20190717_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='jobNumber',
            field=models.CharField(max_length=10, unique=True, verbose_name='工号'),
        ),
    ]
