# Generated by Django 2.2.3 on 2019-09-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_auto_20190720_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': '员工等级', 'verbose_name_plural': '员工等级'},
        ),
        migrations.AlterModelOptions(
            name='vipuser',
            options={'verbose_name': '工作人员', 'verbose_name_plural': '工作人员'},
        ),
        migrations.AlterModelOptions(
            name='vipusertype',
            options={'verbose_name': '员工分组', 'verbose_name_plural': '员工分组'},
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='员工等级', to='office.Level', verbose_name='用户等级'),
        ),
    ]
