# Generated by Django 2.2.3 on 2019-10-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_auto_20191010_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipuser',
            old_name='level',
            new_name='lev',
        ),
    ]
