# Generated by Django 2.2.3 on 2019-10-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_auto_20191010_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipuser',
            old_name='lev',
            new_name='level',
        ),
    ]
