# Generated by Django 2.2.3 on 2019-10-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_auto_20191010_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='员工等级', to='office.Level', verbose_name='用户等级'),
        ),
    ]
