# Generated by Django 2.2.3 on 2019-08-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(default='NaN', max_length=100)),
                ('secret', models.CharField(default='NaN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('name', models.CharField(default='NaN', max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(default='NaN', max_length=11, verbose_name='联系电话')),
                ('unionCode', models.CharField(default='NaN', max_length=50, verbose_name='unionCode')),
                ('loginCode', models.CharField(default='NaN', max_length=50, verbose_name='微信登录凭证')),
                ('division', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snack.Division', verbose_name='单位/院系/部门')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
