# Generated by Django 2.1.7 on 2019-03-31 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='NaN', max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='NaN', max_length=10, verbose_name='单位名称')),
                ('clas', models.CharField(default='NaN', max_length=10, verbose_name='院系')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='NaN', max_length=10, verbose_name='用户编码')),
                ('section', models.CharField(default='NaN', max_length=20, verbose_name='单位')),
                ('clas', models.CharField(default='NaN', max_length=20, verbose_name='院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(default='NaN', max_length=11, verbose_name='报修单号')),
                ('model', models.CharField(max_length=20, verbose_name='机器型号')),
                ('faultDescription', models.TextField(verbose_name='故障描述')),
                ('evaluation', models.CharField(max_length=200, verbose_name='订单评价')),
                ('level', models.CharField(choices=[('5', '五星'), ('4', '四星'), ('3', '三星'), ('2', '二星'), ('1', '一星')], max_length=2, verbose_name='星级')),
                ('orderStatus', models.CharField(choices=[('0', '审核中'), ('1', '等待维修'), ('2', '已完修'), ('3', '已验收')], max_length=2, verbose_name='订单状态')),
                ('orderLog', models.TextField(verbose_name='订单日志')),
                ('serviceStatus', models.CharField(choices=[('0', '下派中'), ('1', '待维修'), ('2', '维修中'), ('3', '维修完成')], max_length=2, verbose_name='服务状态')),
                ('serviceLog', models.TextField(verbose_name='服务日志')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Address', verbose_name='报修地址')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.BooleanField(default=False, verbose_name='审核员审核')),
                ('belongTo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.BelongTo', verbose_name='单位/院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongTo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.BelongTo', verbose_name='单位/院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(default='NaN', max_length=10, verbose_name='服务类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('name', models.CharField(default='NaN', max_length=10, verbose_name='姓名')),
                ('userType', models.CharField(choices=[('VU', 'vipUser'), ('SU', 'scholarUser'), ('CU', 'user')], default='CU', max_length=2, verbose_name='用户类型')),
                ('tel', models.CharField(default='NaN', max_length=11, verbose_name='联系电话')),
                ('unionCode', models.CharField(default='NaN', max_length=50, verbose_name='unionCode')),
                ('loginCode', models.CharField(default='NaN', max_length=50, verbose_name='微信登录凭证')),
            ],
        ),
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNumber', models.CharField(default='NaN', max_length=10, verbose_name='工号')),
                ('address', models.CharField(default='NaN', max_length=50, verbose_name='地址')),
                ('hiredate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间')),
                ('hire', models.BooleanField(default=True, verbose_name='就职状态')),
                ('dimissionTime', models.DateTimeField(blank=True, verbose_name='离职时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vUser', to='public.User')),
            ],
        ),
        migrations.CreateModel(
            name='VipUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='NaN', max_length=10, verbose_name='服务商')),
                ('vipUserType', models.CharField(default='NaN', max_length=10, verbose_name='用户种类')),
                ('level', models.CharField(default='NaN', max_length=4, verbose_name='技术等级')),
                ('rate', models.FloatField(default=0, verbose_name='提成率')),
            ],
        ),
        migrations.AddField(
            model_name='vipuser',
            name='vipUserInfo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.VipUserInfo', verbose_name='用户信息'),
        ),
        migrations.AddField(
            model_name='scholaruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sUser', to='public.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='public.User', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='order',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.ServiceType', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='technician', to='public.User', verbose_name='维修员'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cUser', to='public.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='Client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.Client'),
        ),
    ]
