# Generated by Django 2.1.7 on 2019-03-26 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='NaN', max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(default='NaN', max_length=10, verbose_name='服务商')),
            ],
        ),
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=10, verbose_name='院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='NaN', max_length=10, verbose_name='用户编码')),
                ('section', models.CharField(default='NaN', max_length=20, verbose_name='单位')),
                ('clas', models.CharField(default='NaN', max_length=20, verbose_name='院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TC_PT', '技术实习'), ('TC_PM', '技术初级'), ('TC_TM', '技术中级'), ('TC_AD', '技术高级'), ('FN_PT', '财务实习'), ('FN_DF', '财务正式'), ('AT_PT', '调度实习'), ('AT_DF', '调度正式'), ('VD_PT', '销售实习'), ('VD_DF', '销售正式')], max_length=5, verbose_name='技术等级')),
                ('rate', models.FloatField(verbose_name='提成率')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(default='NaN', max_length=11, verbose_name='报修单号')),
                ('model', models.CharField(max_length=20, verbose_name='机器型号')),
                ('faultDescription', models.TextField(verbose_name='故障描述')),
                ('evaluation', models.CharField(max_length=200, verbose_name='订单评价')),
                ('level', models.CharField(choices=[('5', '五星'), ('4', '四星'), ('3', '三星'), ('2', '二星'), ('1', '一星')], max_length=2, verbose_name='星级')),
                ('orderStatus', models.CharField(choices=[('0', '审核中'), ('1', '等待维修'), ('2', '已完修'), ('3', '已验收')], max_length=2, verbose_name='订单状态')),
                ('orderLog', models.TextField(verbose_name='订单日志')),
                ('serviceStatus', models.CharField(choices=[('0', '下派中'), ('1', '待维修'), ('2', '维修中'), ('3', '维修完成')], max_length=2, verbose_name='服务状态')),
                ('serviceLog', models.TextField(verbose_name='服务日志')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Address', verbose_name='报修地址')),
            ],
        ),
        migrations.CreateModel(
            name='scholarOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.BooleanField(default=False, verbose_name='审核员审核')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Clas', verbose_name='单位/院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Clas', verbose_name='单位/院系/部门')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, verbose_name='单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10, verbose_name='服务类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('name', models.CharField(default='NaN', max_length=10, verbose_name='姓名')),
                ('uesrType', models.CharField(choices=[('VU', 'vipUser'), ('SU', 'scholarUser'), ('CU', 'user')], default='CU', max_length=2, verbose_name='用户类型')),
                ('tel', models.CharField(default='NaN', max_length=11, verbose_name='联系电话')),
                ('unionCode', models.CharField(default='NaN', max_length=50, verbose_name='unionCode')),
                ('loginCode', models.CharField(default='NaN', max_length=50, verbose_name='微信登录凭证')),
            ],
        ),
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNumber', models.CharField(default='NaN', max_length=10, verbose_name='工号')),
                ('address', models.CharField(default='NaN', max_length=50, verbose_name='地址')),
                ('hiredate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间')),
                ('hire', models.BooleanField(default=True, verbose_name='就职状态')),
                ('dimissionTime', models.DateTimeField(blank=True, verbose_name='离职时间')),
                ('uesrType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vUser', to='public.User')),
            ],
        ),
        migrations.CreateModel(
            name='VipUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('TC', '技术'), ('FN', '财务'), ('AT', '调度'), ('VD', '销售')], max_length=2, verbose_name='用户类别')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Agent', verbose_name='服务商')),
            ],
        ),
        migrations.AddField(
            model_name='scholaruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sUser', to='public.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='public.User', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='order',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.ServiceType', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='technician', to='public.User', verbose_name='维修员'),
        ),
        migrations.AddField(
            model_name='level',
            name='vipUserType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.VipUserType', verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cUser', to='public.User'),
        ),
        migrations.AddField(
            model_name='clas',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Section', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='address',
            name='Client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.Client'),
        ),
    ]
