# Generated by Django 2.2.3 on 2019-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(default='NaN', verbose_name='api调用凭证')),
                ('save_time', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('data_line', models.DateTimeField(blank=True, null=True, verbose_name='最后有效时间')),
            ],
        ),
    ]
