# Generated by Django 2.1.7 on 2019-03-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipuser',
            old_name='uesrType',
            new_name='userType',
        ),
    ]
