# Generated by Django 2.2.3 on 2019-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_assesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholaruser',
            name='activation',
            field=models.BooleanField(default=False, verbose_name='用户激活'),
        ),
    ]
