# Generated by Django 2.1.7 on 2019-03-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190326_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uesrType',
            new_name='userType',
        ),
    ]
