# Generated by Django 2.2.3 on 2019-09-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_scholaruser_activation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholaruser',
            options={'verbose_name': '校方审核员', 'verbose_name_plural': '校方审核员'},
        ),
    ]
