# Generated by Django 2.2.3 on 2019-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190929_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionCode', models.CharField(default='NaN', max_length=50, verbose_name='openid')),
                ('unionID', models.CharField(default='NaN', max_length=50, verbose_name='开放平台id')),
            ],
        ),
    ]
