# Generated by Django 2.2.3 on 2019-10-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholaruser',
            name='division',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scholarUser', to='snack.Division', verbose_name='单位/院系/部门'),
        ),
    ]
