# Generated by Django 2.2.3 on 2019-07-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20190717_0938'),
        ('snack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='office.VipUser', verbose_name='维修员'),
        ),
    ]
