# Generated by Django 2.2.3 on 2019-07-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snack.Division', verbose_name='单位/院系/部门'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.CharField(max_length=20, verbose_name='物品型号'),
        ),
    ]
