# Generated by Django 2.2.3 on 2019-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(blank=True, choices=[('五星', '五星'), ('四星', '四星'), ('三星', '三星'), ('二星', '二星'), ('一星', '一星'), ('无', '无')], max_length=2, verbose_name='星级'),
        ),
    ]
