# Generated by Django 2.2.3 on 2019-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_order_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='evaluation',
            field=models.CharField(blank=True, max_length=200, verbose_name='订单评价'),
        ),
    ]
