# Generated by Django 2.2.3 on 2019-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_auto_20190807_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('五星', '五星'), ('四星', '四星'), ('三星', '三星'), ('二星', '二星'), ('一星', '一星'), ('无', '无')], default='无', max_length=2, verbose_name='星级'),
        ),
    ]
