# Generated by Django 2.2.3 on 2019-07-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_auto_20190706_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snack.Division', verbose_name='单位/院系/部门'),
        ),
    ]
