# Generated by Django 2.2.3 on 2019-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0003_auto_20190706_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='clas',
            field=models.CharField(default='NaN', max_length=10, verbose_name='部门'),
        ),
        migrations.DeleteModel(
            name='VipUser',
        ),
        migrations.DeleteModel(
            name='VipUserInfo',
        ),
    ]
