# Generated by Django 2.2.3 on 2019-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0004_auto_20190914_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('审核中', '审核中'), ('待维修', '等待维修'), ('已完修', '已完修'), ('已验收', '已验收'), ('已撤销', '已撤销')], default='审核中', max_length=4, verbose_name='订单状态'),
        ),
    ]
