# Generated by Django 2.2.3 on 2019-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0004_auto_20190710_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costList',
            field=models.TextField(default='NaN', verbose_name='维修明细'),
        ),
        migrations.AddField(
            model_name='order',
            name='faultContent',
            field=models.TextField(default='NaN', verbose_name='故障内容'),
        ),
        migrations.AlterField(
            model_name='order',
            name='faultDescription',
            field=models.TextField(default='NaN', verbose_name='故障描述'),
        ),
    ]
