# Generated by Django 2.2.3 on 2019-09-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0005_auto_20190928_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='costList',
            field=models.TextField(verbose_name='维修明细'),
        ),
    ]
