# Generated by Django 2.2.3 on 2019-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0006_order_is_assess'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='snack.Order', verbose_name='订单'),
        ),
    ]
