# Generated by Django 2.2.3 on 2019-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0006_auto_20190928_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_up',
            field=models.CharField(default='0', max_length=10, verbose_name='合计'),
        ),
    ]
