# Generated by Django 2.2.3 on 2019-08-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0007_image_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScholarUser',
        ),
    ]
