# Generated by Django 2.2.3 on 2019-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0007_order_add_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='costList',
            field=models.TextField(blank=True, verbose_name='维修明细'),
        ),
    ]
