# Generated by Django 2.2.3 on 2019-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0009_auto_20190929_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='unionID',
            field=models.CharField(default='NaN', max_length=50, verbose_name='unionID'),
        ),
    ]
