# Generated by Django 2.2.3 on 2019-10-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0011_order_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no',
            field=models.CharField(blank=True, default='NaN', max_length=20, verbose_name='资产编号'),
        ),
    ]
